### ISSUE TITLE
This one is wrong

### ISSUE THREAD

**Issue by soipo** [Bethania-Freitas/beacademy-devstart-projeto-individual#1]
https://github.com/Bethania-Freitas/beacademy-devstart-projeto-individual/blob/df84ec1a78750c51dcf2da99c07e19e49c9fe50e/EnsaioVirtual/database/migrations/2022_06_28_184233_create_setlists_table.php#L22

this migration is wrong, perhaps you want to have $table->string('id_lyric');

**Comment by Bethania-Freitas** [comment]
Verdade!   Escrevi errado!!  Obrigada!
