### ISSUE TITLE
Wrong migration

### ISSUE THREAD

**Issue by soipo** [Bethania-Freitas/beacademy-devstart-projeto-individual#2]
https://github.com/Bethania-Freitas/beacademy-devstart-projeto-individual/blob/df84ec1a78750c51dcf2da99c07e19e49c9fe50e/EnsaioVirtual/database/migrations/2022_07_08_190823_create_files_table.php#L26

Perhaps this is what you want ?

`        Schema::create('files', function (Blueprint $table) {
            $table->id();
            $table->string('orig_filename', 100)->nullable();
            $table->string('mime_type', 50)->nullable();
            $table->bigInteger('filesize');
            $table->text('content')->nullable();
            $table->unsignedBigInteger('id_lyric')->nullable();
            $table->timestamps();
        });

        Schema::table('files', function (Blueprint $table) {
            $table->foreign('id_lyric')->references('id')->on('setlists')->onDelete('CASCADE');
        });`

**Comment by Bethania-Freitas** [comment]
Feito.   Obrigada!
