### ISSUE TITLE
No view home exists, what do you want to do here?

### ISSUE THREAD

**Issue by soipo** [Bethania-Freitas/beacademy-devstart-projeto-individual#3]
https://github.com/Bethania-Freitas/beacademy-devstart-projeto-individual/blob/df84ec1a78750c51dcf2da99c07e19e49c9fe50e/EnsaioVirtual/routes/web.php#L14

**Comment by Bethania-Freitas** [comment]
Eu pretendo fazer a home ainda.   MInha ideia é jogar na home a agenda dos shows para que qualquer usuário possa visualizar sem precisar logar no site.
