### ISSUE TITLE
where is Hora ? Your database requires a Hora date, a bit useless  if you are requiring a date

### ISSUE THREAD

**Issue by soipo** [Bethania-Freitas/beacademy-devstart-projeto-individual#4]
https://github.com/Bethania-Freitas/beacademy-devstart-projeto-individual/blob/df84ec1a78750c51dcf2da99c07e19e49c9fe50e/EnsaioVirtual/app/Http/Requests/RehearsalRequest.php#L29

You can just save the date as datetime in stead or if you really want two fields you need a date and a date time/ or a string containing the hour

**Comment by Bethania-Freitas** [comment]
Arrumei!!   :)    Muito obrigada!!!
